[CBRD-24906] The problem of performing a cross join by changing to the '0 <> 0' condition when the WHERE clause is always false (#4510)
http://jira.cubrid.org/browse/CBRD-24906

Revert the changes in CBRD-24735 (#4240).

An error occurs when the following query is executed.
   ```
   drop table if exists t1, t2;
   create table t1 (c1 int primary key, c2 int, c3 int);
   create table t2 (c1 int primary key, c2 int, c3 int);
   
   select /*+ recompile */ count (*)
   from t1 as a
   where a.c1 in (select b.c2 from t2 as b where a.c1 = b.c1 and b.c3 = 1 and b.c3 = 2);
   
   /*
   Query plan:
   
   iscan
       class: a node[0]
       index: pk_t1_c1 term[0] (covers)
       cost:  1 card 0
   
   Query stmt:
   
   select count(*) from t1 a where a.c1 in null
   
   ERROR: System error (index plan generation - invalid key value) in src/parser/xasl_generation.c (line: 12174)
   */
   ```

And other side-effects are expected.
So, we will revert CBRD-24735 and then change the approach to resolve the issue.